# Generated by Django 4.1.1 on 2022-09-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
